# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-09 08:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smartmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='lon',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(default=datetime.datetime(2017, 8, 9, 8, 26, 50, 87948, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.CharField(default=datetime.datetime(2017, 8, 9, 8, 26, 56, 842275, tzinfo=utc), max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.CharField(max_length=25),
        ),
    ]
